// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEcDpJ4ZscDmwNcQiNkzshIynHUR2rP9Q',
    appId: '1:345124084089:web:836efe6aef476690b277a8',
    messagingSenderId: '345124084089',
    projectId: 'majdoleen-4601a',
    authDomain: 'majdoleen-4601a.firebaseapp.com',
    storageBucket: 'majdoleen-4601a.firebasestorage.app',
    measurementId: 'G-E622K1VL8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBstorxreaSK7976Ms6xkM8l2HrIlhs1vQ',
    appId: '1:345124084089:android:c7aa75717f577d53b277a8',
    messagingSenderId: '345124084089',
    projectId: 'majdoleen-4601a',
    storageBucket: 'majdoleen-4601a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkG8UW2ORPWJTRtyZ0A8_QRou9ym3cjZc',
    appId: '1:345124084089:ios:45b4ae012a624933b277a8',
    messagingSenderId: '345124084089',
    projectId: 'majdoleen-4601a',
    storageBucket: 'majdoleen-4601a.firebasestorage.app',
    iosBundleId: 'com.example.majdoleenSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkG8UW2ORPWJTRtyZ0A8_QRou9ym3cjZc',
    appId: '1:345124084089:ios:45b4ae012a624933b277a8',
    messagingSenderId: '345124084089',
    projectId: 'majdoleen-4601a',
    storageBucket: 'majdoleen-4601a.firebasestorage.app',
    iosBundleId: 'com.example.majdoleenSeller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEcDpJ4ZscDmwNcQiNkzshIynHUR2rP9Q',
    appId: '1:345124084089:web:23d7af6bd0e2eff7b277a8',
    messagingSenderId: '345124084089',
    projectId: 'majdoleen-4601a',
    authDomain: 'majdoleen-4601a.firebaseapp.com',
    storageBucket: 'majdoleen-4601a.firebasestorage.app',
    measurementId: 'G-3DF9X3YZX6',
  );
}
